package com.loadtrack.util;

import com.lowagie.text.*;
import com.lowagie.text.pdf.PdfPCell;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfWriter;
import org.springframework.stereotype.Component;

import java.awt.Color;
import java.io.ByteArrayOutputStream;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;

@Component
public class ReportPdfBuilder {

    private static final Font TITLE_FONT = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 18, new Color(25, 118, 210));
    private static final Font META_FONT = FontFactory.getFont(FontFactory.HELVETICA, 10, Color.DARK_GRAY);
    private static final Font HEADER_FONT = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 9, Color.WHITE);
    private static final Font CELL_FONT = FontFactory.getFont(FontFactory.HELVETICA, 9, Color.BLACK);
    private static final Font FOOTER_FONT = FontFactory.getFont(FontFactory.HELVETICA_OBLIQUE, 8, Color.GRAY);
    private static final DateTimeFormatter DT = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm");

    public byte[] build(String title, String subtitle, List<String> headers, List<List<Object>> rows) {
        Document doc = new Document(PageSize.A4.rotate(), 30, 30, 30, 30); // landscape for wide tables
        ByteArrayOutputStream baos = new ByteArrayOutputStream();
        PdfWriter.getInstance(doc, baos);
        doc.open();

        // Title
        Paragraph t = new Paragraph(title, TITLE_FONT);
        t.setAlignment(Element.ALIGN_LEFT);
        doc.add(t);

        if (subtitle != null && !subtitle.isBlank()) {
            Paragraph s = new Paragraph(subtitle, META_FONT);
            s.setSpacingAfter(6);
            doc.add(s);
        }

        Paragraph generated = new Paragraph(
                "Generated by LoadTrack on " + DT.format(LocalDateTime.now()) + "  ·  " + rows.size() + " row(s)",
                META_FONT);
        generated.setSpacingAfter(10);
        doc.add(generated);

        // Table
        PdfPTable table = new PdfPTable(headers.size());
        table.setWidthPercentage(100);
        table.setHeaderRows(1);

        for (String h : headers) {
            PdfPCell cell = new PdfPCell(new Phrase(h, HEADER_FONT));
            cell.setBackgroundColor(new Color(25, 118, 210));
            cell.setPadding(6);
            cell.setBorderColor(new Color(200, 200, 200));
            table.addCell(cell);
        }

        for (List<Object> row : rows) {
            for (Object v : row) {
                PdfPCell cell = new PdfPCell(new Phrase(v == null ? "" : v.toString(), CELL_FONT));
                cell.setPadding(5);
                cell.setBorderColor(new Color(220, 220, 220));
                table.addCell(cell);
            }
        }

        if (rows.isEmpty()) {
            PdfPCell empty = new PdfPCell(new Phrase("No data for the selected filters.", CELL_FONT));
            empty.setColspan(headers.size());
            empty.setHorizontalAlignment(Element.ALIGN_CENTER);
            empty.setPadding(20);
            table.addCell(empty);
        }

        doc.add(table);

        Paragraph footer = new Paragraph("LoadTrack — Truck Operations Management", FOOTER_FONT);
        footer.setAlignment(Element.ALIGN_CENTER);
        footer.setSpacingBefore(15);
        doc.add(footer);

        doc.close();
        return baos.toByteArray();
    }
}
